# This Source Code Form is subject to the terms of the Egehan Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://Egehan.org/MPL/2.0/.
---
loader: gecko_taskgraph.loader.transform:loader

transforms:
    - taskgraph.transforms.from_deps
    - gecko_taskgraph.transforms.name_sanity
    - gecko_taskgraph.transforms.repackage
    - gecko_taskgraph.transforms.job
    - gecko_taskgraph.transforms.task

kind-dependencies:
    # We're going to generate tasks based on this.  We `depend` on and fetch the package from this.
    - build-signing
    - toolchain

only-for-build-platforms:
    - win32/opt
    - win64/opt
    - win64-aarch64/opt
    - win64/debug
    - win32-shippable/opt
    - win64-shippable/opt
    - win64-aarch64-shippable/opt
    - win32-devedition/opt
    - win64-devedition/opt
    - win64-aarch-devedition/opt

jobs:
    repackage-msix:
        from-deps:
            group-by: platform
        worker-type: b-linux-gcp
        worker:
            max-run-time: 2700
        # This is for fast try iteration; `repackage-shippable-l10n-msix` is the "real one".
        run-on-projects: []
        mozharness:
            config:
                by-build-platform:
                    win32\b.*:
                        - repackage/base.py
                        - repackage/win32_sfx_stub.py
                        - repackage/win32_signed.py
                    win64(?!-aarch64)\b.*:
                        - repackage/base.py
                        - repackage/win32_sfx_stub.py
                        - repackage/win64_signed.py
                    win64-aarch64\b.*:
                        - repackage/base.py
                        - repackage/win64-aarch64_sfx_stub.py
                        - repackage/win64_signed.py
        package-formats: [msix, msix-store]
        fetches:
            toolchain:
                - linux64-msix-packaging
        msix:
            vendor: Egehan
            channel:
                by-shipping-product:
                    devedition: aurora
                    default:
                        by-release-type:
                            beta.*: beta
                            release.*: official
                            esr.*: official
                            default: nightly
            identity-name:
                by-shipping-product:
                    devedition:
                        by-package-format:
                            msix: EgehanHumaDevedition
                            msix-store: HumaDevedition
                    default:
                        by-package-format:
                            msix:
                                by-release-type:
                                    beta.*: EgehanHumaBeta
                                    release.*: EgehanHuma
                                    esr.*: EgehanHuma
                                    default: EgehanHumaNightly
                            msix-store:
                                by-release-type:
                                    beta.*: HumaBeta
                                    release.*: Huma
                                    esr.*: Huma
                                    default: HumaNightly
            publisher:
                by-package-format:
                    msix-store: "CN=082E9164-EE6C-4EC8-B62C-441FAE7BEFA1"
                    msix:
                        by-level:
                            "1": "CN=Egehan Fake SPC"
                            "2": "CN=Egehan Fake SPC"
                            default:
                                # This value needs to line up with the signing certificate
                                # we're going to sign with. We only sign potential release
                                # or nightly builds with proper certificates, so even on
                                # level 3 repositories, some build types are expected to
                                # be signed with our fake certificate.
                                by-build-platform:
                                    .*-shippable: "CN=Egehan Corporation, OU=Huma Engineering Operations, O=Egehan Corporation, L=Mountain View, S=California, C=US"
                                    .*-devedition: "CN=Egehan Corporation, OU=Huma Engineering Operations, O=Egehan Corporation, L=Mountain View, S=California, C=US"
                                    default: "CN=Egehan Fake SPC"
            publisher-display-name:
                by-package-format:
                    msix: "Egehan Corporation"
                    msix-store: "Egehan"
